// Generated by gencpp from file autolab_core/RigidTransformPublisherRequest.msg
// DO NOT EDIT!


#ifndef AUTOLAB_CORE_MESSAGE_RIGIDTRANSFORMPUBLISHERREQUEST_H
#define AUTOLAB_CORE_MESSAGE_RIGIDTRANSFORMPUBLISHERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace autolab_core
{
template <class ContainerAllocator>
struct RigidTransformPublisherRequest_
{
  typedef RigidTransformPublisherRequest_<ContainerAllocator> Type;

  RigidTransformPublisherRequest_()
    : x_trans(0.0)
    , y_trans(0.0)
    , z_trans(0.0)
    , w_rot(0.0)
    , x_rot(0.0)
    , y_rot(0.0)
    , z_rot(0.0)
    , from_frame()
    , to_frame()
    , mode()  {
    }
  RigidTransformPublisherRequest_(const ContainerAllocator& _alloc)
    : x_trans(0.0)
    , y_trans(0.0)
    , z_trans(0.0)
    , w_rot(0.0)
    , x_rot(0.0)
    , y_rot(0.0)
    , z_rot(0.0)
    , from_frame(_alloc)
    , to_frame(_alloc)
    , mode(_alloc)  {
  (void)_alloc;
    }



   typedef double _x_trans_type;
  _x_trans_type x_trans;

   typedef double _y_trans_type;
  _y_trans_type y_trans;

   typedef double _z_trans_type;
  _z_trans_type z_trans;

   typedef double _w_rot_type;
  _w_rot_type w_rot;

   typedef double _x_rot_type;
  _x_rot_type x_rot;

   typedef double _y_rot_type;
  _y_rot_type y_rot;

   typedef double _z_rot_type;
  _z_rot_type z_rot;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _from_frame_type;
  _from_frame_type from_frame;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _to_frame_type;
  _to_frame_type to_frame;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _mode_type;
  _mode_type mode;





  typedef boost::shared_ptr< ::autolab_core::RigidTransformPublisherRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autolab_core::RigidTransformPublisherRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RigidTransformPublisherRequest_

typedef ::autolab_core::RigidTransformPublisherRequest_<std::allocator<void> > RigidTransformPublisherRequest;

typedef boost::shared_ptr< ::autolab_core::RigidTransformPublisherRequest > RigidTransformPublisherRequestPtr;
typedef boost::shared_ptr< ::autolab_core::RigidTransformPublisherRequest const> RigidTransformPublisherRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autolab_core::RigidTransformPublisherRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autolab_core::RigidTransformPublisherRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace autolab_core

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::autolab_core::RigidTransformPublisherRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autolab_core::RigidTransformPublisherRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autolab_core::RigidTransformPublisherRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autolab_core::RigidTransformPublisherRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autolab_core::RigidTransformPublisherRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autolab_core::RigidTransformPublisherRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autolab_core::RigidTransformPublisherRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2414e9e80f6a0faf446e445b137fbf6c";
  }

  static const char* value(const ::autolab_core::RigidTransformPublisherRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2414e9e80f6a0fafULL;
  static const uint64_t static_value2 = 0x446e445b137fbf6cULL;
};

template<class ContainerAllocator>
struct DataType< ::autolab_core::RigidTransformPublisherRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autolab_core/RigidTransformPublisherRequest";
  }

  static const char* value(const ::autolab_core::RigidTransformPublisherRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autolab_core::RigidTransformPublisherRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x_trans\n\
float64 y_trans\n\
float64 z_trans\n\
float64 w_rot\n\
float64 x_rot\n\
float64 y_rot\n\
float64 z_rot\n\
string from_frame\n\
string to_frame\n\
string mode\n\
";
  }

  static const char* value(const ::autolab_core::RigidTransformPublisherRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autolab_core::RigidTransformPublisherRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x_trans);
      stream.next(m.y_trans);
      stream.next(m.z_trans);
      stream.next(m.w_rot);
      stream.next(m.x_rot);
      stream.next(m.y_rot);
      stream.next(m.z_rot);
      stream.next(m.from_frame);
      stream.next(m.to_frame);
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RigidTransformPublisherRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autolab_core::RigidTransformPublisherRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::autolab_core::RigidTransformPublisherRequest_<ContainerAllocator>& v)
  {
    s << indent << "x_trans: ";
    Printer<double>::stream(s, indent + "  ", v.x_trans);
    s << indent << "y_trans: ";
    Printer<double>::stream(s, indent + "  ", v.y_trans);
    s << indent << "z_trans: ";
    Printer<double>::stream(s, indent + "  ", v.z_trans);
    s << indent << "w_rot: ";
    Printer<double>::stream(s, indent + "  ", v.w_rot);
    s << indent << "x_rot: ";
    Printer<double>::stream(s, indent + "  ", v.x_rot);
    s << indent << "y_rot: ";
    Printer<double>::stream(s, indent + "  ", v.y_rot);
    s << indent << "z_rot: ";
    Printer<double>::stream(s, indent + "  ", v.z_rot);
    s << indent << "from_frame: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.from_frame);
    s << indent << "to_frame: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.to_frame);
    s << indent << "mode: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOLAB_CORE_MESSAGE_RIGIDTRANSFORMPUBLISHERREQUEST_H
