// Generated by gencpp from file autolab_core/RigidTransformListenerRequest.msg
// DO NOT EDIT!


#ifndef AUTOLAB_CORE_MESSAGE_RIGIDTRANSFORMLISTENERREQUEST_H
#define AUTOLAB_CORE_MESSAGE_RIGIDTRANSFORMLISTENERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace autolab_core
{
template <class ContainerAllocator>
struct RigidTransformListenerRequest_
{
  typedef RigidTransformListenerRequest_<ContainerAllocator> Type;

  RigidTransformListenerRequest_()
    : from_frame()
    , to_frame()  {
    }
  RigidTransformListenerRequest_(const ContainerAllocator& _alloc)
    : from_frame(_alloc)
    , to_frame(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _from_frame_type;
  _from_frame_type from_frame;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _to_frame_type;
  _to_frame_type to_frame;





  typedef boost::shared_ptr< ::autolab_core::RigidTransformListenerRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autolab_core::RigidTransformListenerRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RigidTransformListenerRequest_

typedef ::autolab_core::RigidTransformListenerRequest_<std::allocator<void> > RigidTransformListenerRequest;

typedef boost::shared_ptr< ::autolab_core::RigidTransformListenerRequest > RigidTransformListenerRequestPtr;
typedef boost::shared_ptr< ::autolab_core::RigidTransformListenerRequest const> RigidTransformListenerRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autolab_core::RigidTransformListenerRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autolab_core::RigidTransformListenerRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace autolab_core

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::autolab_core::RigidTransformListenerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autolab_core::RigidTransformListenerRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autolab_core::RigidTransformListenerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autolab_core::RigidTransformListenerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autolab_core::RigidTransformListenerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autolab_core::RigidTransformListenerRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autolab_core::RigidTransformListenerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "926bcdc77e020fe1b0dab9093941bca3";
  }

  static const char* value(const ::autolab_core::RigidTransformListenerRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x926bcdc77e020fe1ULL;
  static const uint64_t static_value2 = 0xb0dab9093941bca3ULL;
};

template<class ContainerAllocator>
struct DataType< ::autolab_core::RigidTransformListenerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autolab_core/RigidTransformListenerRequest";
  }

  static const char* value(const ::autolab_core::RigidTransformListenerRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autolab_core::RigidTransformListenerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string from_frame\n\
string to_frame\n\
";
  }

  static const char* value(const ::autolab_core::RigidTransformListenerRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autolab_core::RigidTransformListenerRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.from_frame);
      stream.next(m.to_frame);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RigidTransformListenerRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autolab_core::RigidTransformListenerRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::autolab_core::RigidTransformListenerRequest_<ContainerAllocator>& v)
  {
    s << indent << "from_frame: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.from_frame);
    s << indent << "to_frame: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.to_frame);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOLAB_CORE_MESSAGE_RIGIDTRANSFORMLISTENERREQUEST_H
