// Generated by gencpp from file yumipy/ROSYumiArm.msg
// DO NOT EDIT!


#ifndef YUMIPY_MESSAGE_ROSYUMIARM_H
#define YUMIPY_MESSAGE_ROSYUMIARM_H

#include <ros/service_traits.h>


#include <yumipy/ROSYumiArmRequest.h>
#include <yumipy/ROSYumiArmResponse.h>


namespace yumipy
{

struct ROSYumiArm
{

typedef ROSYumiArmRequest Request;
typedef ROSYumiArmResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ROSYumiArm
} // namespace yumipy


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::yumipy::ROSYumiArm > {
  static const char* value()
  {
    return "a5f31b322bc70c99cdf226b9d88321e7";
  }

  static const char* value(const ::yumipy::ROSYumiArm&) { return value(); }
};

template<>
struct DataType< ::yumipy::ROSYumiArm > {
  static const char* value()
  {
    return "yumipy/ROSYumiArm";
  }

  static const char* value(const ::yumipy::ROSYumiArm&) { return value(); }
};


// service_traits::MD5Sum< ::yumipy::ROSYumiArmRequest> should match 
// service_traits::MD5Sum< ::yumipy::ROSYumiArm > 
template<>
struct MD5Sum< ::yumipy::ROSYumiArmRequest>
{
  static const char* value()
  {
    return MD5Sum< ::yumipy::ROSYumiArm >::value();
  }
  static const char* value(const ::yumipy::ROSYumiArmRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::yumipy::ROSYumiArmRequest> should match 
// service_traits::DataType< ::yumipy::ROSYumiArm > 
template<>
struct DataType< ::yumipy::ROSYumiArmRequest>
{
  static const char* value()
  {
    return DataType< ::yumipy::ROSYumiArm >::value();
  }
  static const char* value(const ::yumipy::ROSYumiArmRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::yumipy::ROSYumiArmResponse> should match 
// service_traits::MD5Sum< ::yumipy::ROSYumiArm > 
template<>
struct MD5Sum< ::yumipy::ROSYumiArmResponse>
{
  static const char* value()
  {
    return MD5Sum< ::yumipy::ROSYumiArm >::value();
  }
  static const char* value(const ::yumipy::ROSYumiArmResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::yumipy::ROSYumiArmResponse> should match 
// service_traits::DataType< ::yumipy::ROSYumiArm > 
template<>
struct DataType< ::yumipy::ROSYumiArmResponse>
{
  static const char* value()
  {
    return DataType< ::yumipy::ROSYumiArm >::value();
  }
  static const char* value(const ::yumipy::ROSYumiArmResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // YUMIPY_MESSAGE_ROSYUMIARM_H
