// Generated by gencpp from file yumipy/ROSYumiArmResponse.msg
// DO NOT EDIT!


#ifndef YUMIPY_MESSAGE_ROSYUMIARMRESPONSE_H
#define YUMIPY_MESSAGE_ROSYUMIARMRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yumipy
{
template <class ContainerAllocator>
struct ROSYumiArmResponse_
{
  typedef ROSYumiArmResponse_<ContainerAllocator> Type;

  ROSYumiArmResponse_()
    : ret()  {
    }
  ROSYumiArmResponse_(const ContainerAllocator& _alloc)
    : ret(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _ret_type;
  _ret_type ret;





  typedef boost::shared_ptr< ::yumipy::ROSYumiArmResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yumipy::ROSYumiArmResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ROSYumiArmResponse_

typedef ::yumipy::ROSYumiArmResponse_<std::allocator<void> > ROSYumiArmResponse;

typedef boost::shared_ptr< ::yumipy::ROSYumiArmResponse > ROSYumiArmResponsePtr;
typedef boost::shared_ptr< ::yumipy::ROSYumiArmResponse const> ROSYumiArmResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yumipy::ROSYumiArmResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yumipy::ROSYumiArmResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace yumipy

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::yumipy::ROSYumiArmResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yumipy::ROSYumiArmResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yumipy::ROSYumiArmResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yumipy::ROSYumiArmResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yumipy::ROSYumiArmResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yumipy::ROSYumiArmResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yumipy::ROSYumiArmResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c7030931189f40243cd08ed0e4c0bac7";
  }

  static const char* value(const ::yumipy::ROSYumiArmResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc7030931189f4024ULL;
  static const uint64_t static_value2 = 0x3cd08ed0e4c0bac7ULL;
};

template<class ContainerAllocator>
struct DataType< ::yumipy::ROSYumiArmResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yumipy/ROSYumiArmResponse";
  }

  static const char* value(const ::yumipy::ROSYumiArmResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yumipy::ROSYumiArmResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string ret\n\
\n\
";
  }

  static const char* value(const ::yumipy::ROSYumiArmResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yumipy::ROSYumiArmResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ret);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ROSYumiArmResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yumipy::ROSYumiArmResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yumipy::ROSYumiArmResponse_<ContainerAllocator>& v)
  {
    s << indent << "ret: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.ret);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YUMIPY_MESSAGE_ROSYUMIARMRESPONSE_H
