// Generated by gencpp from file yumipy/ROSYumiArmRequest.msg
// DO NOT EDIT!


#ifndef YUMIPY_MESSAGE_ROSYUMIARMREQUEST_H
#define YUMIPY_MESSAGE_ROSYUMIARMREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yumipy
{
template <class ContainerAllocator>
struct ROSYumiArmRequest_
{
  typedef ROSYumiArmRequest_<ContainerAllocator> Type;

  ROSYumiArmRequest_()
    : func()
    , args()
    , kwargs()  {
    }
  ROSYumiArmRequest_(const ContainerAllocator& _alloc)
    : func(_alloc)
    , args(_alloc)
    , kwargs(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _func_type;
  _func_type func;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _args_type;
  _args_type args;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _kwargs_type;
  _kwargs_type kwargs;





  typedef boost::shared_ptr< ::yumipy::ROSYumiArmRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yumipy::ROSYumiArmRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ROSYumiArmRequest_

typedef ::yumipy::ROSYumiArmRequest_<std::allocator<void> > ROSYumiArmRequest;

typedef boost::shared_ptr< ::yumipy::ROSYumiArmRequest > ROSYumiArmRequestPtr;
typedef boost::shared_ptr< ::yumipy::ROSYumiArmRequest const> ROSYumiArmRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yumipy::ROSYumiArmRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yumipy::ROSYumiArmRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace yumipy

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::yumipy::ROSYumiArmRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yumipy::ROSYumiArmRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yumipy::ROSYumiArmRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yumipy::ROSYumiArmRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yumipy::ROSYumiArmRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yumipy::ROSYumiArmRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yumipy::ROSYumiArmRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "31cc66bd1f2473b7ca0f1a269a335554";
  }

  static const char* value(const ::yumipy::ROSYumiArmRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x31cc66bd1f2473b7ULL;
  static const uint64_t static_value2 = 0xca0f1a269a335554ULL;
};

template<class ContainerAllocator>
struct DataType< ::yumipy::ROSYumiArmRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yumipy/ROSYumiArmRequest";
  }

  static const char* value(const ::yumipy::ROSYumiArmRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yumipy::ROSYumiArmRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string func\n\
string args\n\
string kwargs\n\
";
  }

  static const char* value(const ::yumipy::ROSYumiArmRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yumipy::ROSYumiArmRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.func);
      stream.next(m.args);
      stream.next(m.kwargs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ROSYumiArmRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yumipy::ROSYumiArmRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yumipy::ROSYumiArmRequest_<ContainerAllocator>& v)
  {
    s << indent << "func: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.func);
    s << indent << "args: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.args);
    s << indent << "kwargs: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.kwargs);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YUMIPY_MESSAGE_ROSYUMIARMREQUEST_H
