// Generated by gencpp from file ddynamic_reconfigure/TutorialParams.msg
// DO NOT EDIT!


#ifndef DDYNAMIC_RECONFIGURE_MESSAGE_TUTORIALPARAMS_H
#define DDYNAMIC_RECONFIGURE_MESSAGE_TUTORIALPARAMS_H

#include <ros/service_traits.h>


#include <ddynamic_reconfigure/TutorialParamsRequest.h>
#include <ddynamic_reconfigure/TutorialParamsResponse.h>


namespace ddynamic_reconfigure
{

struct TutorialParams
{

typedef TutorialParamsRequest Request;
typedef TutorialParamsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TutorialParams
} // namespace ddynamic_reconfigure


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ddynamic_reconfigure::TutorialParams > {
  static const char* value()
  {
    return "2b2d98973833896677e387258d00296b";
  }

  static const char* value(const ::ddynamic_reconfigure::TutorialParams&) { return value(); }
};

template<>
struct DataType< ::ddynamic_reconfigure::TutorialParams > {
  static const char* value()
  {
    return "ddynamic_reconfigure/TutorialParams";
  }

  static const char* value(const ::ddynamic_reconfigure::TutorialParams&) { return value(); }
};


// service_traits::MD5Sum< ::ddynamic_reconfigure::TutorialParamsRequest> should match 
// service_traits::MD5Sum< ::ddynamic_reconfigure::TutorialParams > 
template<>
struct MD5Sum< ::ddynamic_reconfigure::TutorialParamsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ddynamic_reconfigure::TutorialParams >::value();
  }
  static const char* value(const ::ddynamic_reconfigure::TutorialParamsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ddynamic_reconfigure::TutorialParamsRequest> should match 
// service_traits::DataType< ::ddynamic_reconfigure::TutorialParams > 
template<>
struct DataType< ::ddynamic_reconfigure::TutorialParamsRequest>
{
  static const char* value()
  {
    return DataType< ::ddynamic_reconfigure::TutorialParams >::value();
  }
  static const char* value(const ::ddynamic_reconfigure::TutorialParamsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ddynamic_reconfigure::TutorialParamsResponse> should match 
// service_traits::MD5Sum< ::ddynamic_reconfigure::TutorialParams > 
template<>
struct MD5Sum< ::ddynamic_reconfigure::TutorialParamsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ddynamic_reconfigure::TutorialParams >::value();
  }
  static const char* value(const ::ddynamic_reconfigure::TutorialParamsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ddynamic_reconfigure::TutorialParamsResponse> should match 
// service_traits::DataType< ::ddynamic_reconfigure::TutorialParams > 
template<>
struct DataType< ::ddynamic_reconfigure::TutorialParamsResponse>
{
  static const char* value()
  {
    return DataType< ::ddynamic_reconfigure::TutorialParams >::value();
  }
  static const char* value(const ::ddynamic_reconfigure::TutorialParamsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DDYNAMIC_RECONFIGURE_MESSAGE_TUTORIALPARAMS_H
